### ISSUE TITLE
Enable SourceLink

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/personal-data-sdk-net#4]
**Motivation:** By adding a few SourceLink properties to the `csproj` files, we could allow developers to debug their apps with a full source code of our SDKs (referenced from within the apps as NuGet packages). Even though the SDK is present in the app as a NuGet package, Visual Studio will silently download its source files for the purpose of debugging.

**Howto:** https://github.com/dotnet/sourcelink#using-sourcelink

**Example:** 
- https://github.com/Kentico/delivery-sdk-net/pull/127
- https://github.com/ctaggart/SharpYaml/blob/de09b74f0ea2a470d90eaab04b049d265e59fda0/SharpYaml/Directory.Build.props

**Comment by Simply007** [comment]
Hello @joostas. I've just sent you an invitation to the project. If you accept it, I'll be able to assign the issue to you.

**Comment by joostas** [comment]
Hi @Simply007. Accepted.
